spring : 
  datasource : 
    driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:log4jdbc:h2:mem:hogedb
logging :
  level : 
    jdbc : 
      sqlonly : INFO
      resultsettable : INFO
      connection : off
      sqltiming : off
      audit : off
      resultset : off
    com :
      example :
        demo : DEBUG